version: '3.8'
services:
  postgresdb:
    build: ./postgresdb/
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    build: ./kafka/
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  source-connector:
    build: ./kafka/
    command: connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/debezium.config.properties 
    depends_on:
      - postgresdb
      - kafka

